spring:
  application:
    name: homepage-eureka
server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否从Eureka Server 中获取注册信息，默认是 true。因为目前是单点的Eureka Server，所以不需要从其他的Eureka Server中获取信息
    fetch-registry: false
    # 表示是否将自己注册到 Eureka Server，默认是true
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
